sudo: required
services:
  - docker

before_install:
  - docker build -t paulwhitehand/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulwhitehand/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-2-471063810858"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "AWS_SECRET_KEY"    

